apiVersion: v1
kind: Pod
metadata:
 name: mysql-checker
 namespace: default
spec:
 containers:
  - name: mysql
    image: mysql
  - name: mysql-checker
    image: docker.io/leonelmorais/mysql-checker
    env:
    - name: DB_USER
      value: "root"
    - name: DB_NAME
      value: "demo"
    ports:
      - containerPort: 8080